# Generated by Django 5.0.4 on 2024-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_myuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="Gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="myuser",
            name="name",
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="myuser",
            name="phonenumber",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
