# Generated by Django 5.0.4 on 2024-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_myuser_gender_alter_myuser_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="Gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="phonenumber",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
